name: Validate Model

on:
  workflow_run:
    workflows: ["Train Model"]
    types: [completed]

jobs:
  validate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    outputs:
      accuracy: ${{ steps.metrics.outputs.accuracy }}
      precision: ${{ steps.metrics.outputs.precision }}
      recall: ${{ steps.metrics.outputs.recall }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.14"
          version: "latest"

      - name: Validate model
        run: |
          MODEL_ID="${{github.event.workflow_run.outputs.model_id }}"
          echo "Using model_id: $MODEL_ID"

          uv sync --group dev
          uv pip install -e .
          uv run -m revolutionary_mlops validate "$MODEL_ID" --validate-path data/validate.csv > validate_output.txt

 
      - name: Extract metrics
        id: metrics
        run: |
          ACC=$(awk -F'=' '/^accuracy=/ {print $2}' validate_output.txt | tr -d '\r')
          PREC=$(awk -F'=' '/^precision=/ {print $2}' validate_output.txt | tr -d '\r')
          REC=$(awk -F'=' '/^recall=/ {print $2}' validate_output.txt | tr -d '\r')

          echo "accuracy=$ACC" >> $GITHUB_OUTPUT
          echo "precision=$PREC" >> $GITHUB_OUTPUT
          echo "recall=$REC" >> $GITHUB_OUTPUT

          python3 - <<EOF
          import sys
          acc=float("$ACC"); prec=float("$PREC"); rec=float("$REC")
          if acc < 0.80 or prec < 0.80 or rec < 0.80:
          print("❌ Model quality too low. Failing pipeline.")
          sys.exit(1)
          EOF
